ECHO.%INFO%脚本版本为1.2.8%RESET%
ECHO.%INFO%更新日志：%RESET%
ECHO.%INFO%1.修复“断点续刷”后无法修补boot的问题%RESET%
ECHO.%INFO%2.提升临时环境变量优先级%RESET%
ECHO.%INFO%3.添加9008引导与刷入时错误拦截和错误回显%RESET%
ECHO.%INFO%4.优化局部变量的代码%RESET%
ECHO.%INFO%5.在进入qmmi功能中加入z10%RESET%
ECHO.%INFO%6.优化与修复一键root%RESET%
ECHO.%INFO%7.增加备份相册%RESET%
ECHO.%INFO%8.增加7.1.1和4.4.4安装xp框架%RESET%
ECHO.%INFO%9.增加更多安装应用方式%RESET%
ECHO.%INFO%10.新增/更新8.1机型Root后优化[原生修复]%RESET%
ECHO.%INFO%11.修复自动激活systemplus%RESET%